bind: 127.0.0.1:9000

log_level: info
log_file: /dev/stdout
log_format: console

default_application: default

applications:
  - name: default
    directives: |
      # Keep trace of coraza application name in logs
      SecComponentSignature "coraza-app/default"

      # coraza.conf-recommended from https://github.com/corazawaf/coraza
      Include /usr/share/coraza-spoa/coraza.conf-recommended

      # Custom configuration
      Include /etc/coraza-spoa/default/pre-crs/*.conf

      # OWASP CRS v4 from https://github.com/coreruleset/coreruleset/releases
      Include /usr/share/coraza-spoa/coreruleset/crs-setup.conf.example
      Include /usr/share/coraza-spoa/coreruleset/rules/*.conf

      # custom rule and exclusions
      Include /etc/coraza-spoa/default/post-crs/*.conf

    # HAProxy configured to send SPOE messages:
    # - requests only: set response_check false
    # - requests + responses: set response_check true
    response_check: true

    # Transaction cache lifetime in milliseconds, relevant only with
    # requests + response SPOE messages:
    transaction_ttl_ms: 90000

    log_level: info
    log_file: /var/log/coraza-spoa/default.log
    log_format: json
